### ISSUE TITLE
Classifying and tabulation alignment groups (New counting)

### ISSUE THREAD

**Issue by deliaBlue** [zavolanlab/mirflowz#26]
For the new approach, there won't be any isomiR annotation file and therefore the counting will be  madre directly from the alignments. This is, counting  the identical alignments within the previously extended pre-miR region. 

After the filtering there could be identical multimappers (same edit distance, same number of mismatches and indels). In these cases, the counting will be divided i.e. if mapped to three different regions, each alignment will add 0,33 to each isomiR. 

> MIND that if any multimapper is found to align with a region that is not a pre-miR locus, the counting will still be divided but that alignment will  be discard.

**Comment by uniqueg** [comment]
Couple of comments:

- It is not true that every read has to be counted for a total of 1. Rather, it can be counted by _up to_ 1. If a read has an alignment that does not overlap a feature of interest, it will contribute 0 to the total count. Likewise, if a read has multiple equally good alignments $n$, and only, say, $m$ of them intersect with features of interest, then only a total of $m/n$  will be counted, and of the $m$ alignments will be counted as $1/n$.
- Note that you can actually determine $n$ for each read when you implement the indel vs mismatch filtering. It is simply the number of remaining alignments for each read, after the filtering. You can make use of the SAM tag/optional field `NH` (I've sent the specification previously) to record that $n$, it should make things easier down the road.
- For the pre-miR counting, we would actually use the previous `bedtools` method, counting only alignments that are fully contained within the (extended) pre-miR.
- Incidentally (or not), the alignments counted towards the pre-miRs are exactly the kind of alignments that we also need to consider for the pileups (not every one of them may constitute an isomiR according to our definition, but _all_ the alignments that would represent an isomiR would _also_ be among them!). So you'd do well in trying to modify the `bedtools` call for the pre-miR counting such that only the overlapping alignments are returned. This should speed up the pileup, because any non-miRish alignments will already be discarded.
- You will need to find an efficient solution for the pileups. What I used in the R script is one of them. Libraries like samtools/htslib should be other fast implementations that may or may support pileup counting. In fact, under the hood, they may all use the same C library, not sure. Anyway, the tricky part will be the partial counting. If it weren't for that, it would be trivial to do the job. But because we don't wanna count one per alignment, but rather $1/NH$, you need to find a way how you can hook into the library to return you that rather than an enumeration of alignments per alignment group. I've recently looked at the documentation of the R library (when I prepared the issue for the fractional counting in the ASCII pileup script), and though I didn't actually try to play around with it, it seemed to that it was possible to specify a projection of sorts that might be able to return you the value of a given field or tag from the BAM file (such as `NH`). So that's what you should be looking for. You can also ask on Biostars, an appropriate Stack Exchange or the R/Bioconductor community for help. Or, similarly, you can try to find something like that in htslib or whatever. The important thing is that you understand the issue well enough that you will be able to formulate a clear question.

**Comment by uniqueg** [comment]
Requires solving #27 first

**Comment by deliaBlue** [comment]
The tasks that will close this issue are:

- [ ] #65 
- [ ] #66 
- [ ] #67 
- [ ] #68 
- [ ] #69 
- [ ] #27 
- [ ] #70 
- [ ] #71
